# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
project 'TripOrganizer.xcodeproj'

target 'TripOrganizer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TripOrganizer

pod 'IQKeyboardManagerSwift'
pod 'lottie-ios'
pod 'GooglePlaces', '~> 8.0'
pod 'GoogleSignIn', '~> 7.0.0'
pod 'FBSDKLoginKit'

end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
      end
    end
  end
end
